# Generated by Django 2.2.9 on 2019-12-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_email',
            new_name='author',
        ),
    ]
